print('-=-'*10)
print('''\033[7m         DESAFIO 14           \033[m''')
print('-=-'*10)
print('\033[1mEscreva um programa que converta uma temperatura digitada em ºC e converta para ºF.\033[m')
print('')
print('-=-'*20)
nome = input('Qual e o seu nome? ')
print('-=-'*20)
p = input('Podemos começar {}? '.format(nome))
print('='*30)
c = float(input('Informe a temperatura em ºC: '))
f = ((9 * c) / 5) + 32
print('A temperatura de {}ºC corresponde à {}ºF'.format(c, f))
print('='*30)
print('\033[1mParabéns {}, você concluiu esta tarefa!\033[m'.format(nome))